### ISSUE TITLE
getName \ getId improvements

### ISSUE THREAD

**Issue by dcversus** [sindresorhus/pokemon#10]
Offer a little improvements for the function getName. Second argument is optional, and return object with name on all langs. 

And something similar to getId function. Looking for a name of all dictionaries, if the second argument is not specified.

What do you think about it?

**Comment by sindresorhus** [comment]
> Second argument is optional, and return object with name on all langs.

The second argument is already optional. Completely changing the behavior based on an argument would be bad. We should instead expose a `Set` with the supported languages.

> Looking for a name of all dictionaries, if the second argument is not specified.

Not sure what you mean here. Can you clarify?

**Comment by sindresorhus** [comment]
> We should instead expose a Set with the supported languages.

Done: https://github.com/sindresorhus/pokemon#languages-set

**Comment by sindresorhus** [comment]
Closing for lack of response.
