### ISSUE TITLE
 How about add some other data? such as abilities, types, skills and so on.

### ISSUE THREAD

**Issue by Dafrok** [sindresorhus/pokemon#17]
This wonderful package might be used in some cases like this:

```javascript
import pokemon from 'pokemon'
const snorlax = pokemon.get(143)
console.log(snorlax.ability, snorlax.type)
```

If you want, I'm glad to PR for this work.

**Comment by SamVerschueren** [comment]
That might be a good idea for a `pokedex` package (which can depend on thi sone). This module's purpose is only to provide the names of the pokemon.

**Comment by Dafrok** [comment]
Oops, In my opinion pokemon package more likes an pokemon-object-generator, for Example:

```
import Pokemon from 'pokemon'
const mySnorlax = new Pokemon(143)
mySnorlax.nature = 'Hardy'
mySnorlax.level = 100
mySnorlax.effortPoint.atk = 252
mySnorlax.getAtk() // => 351
```

Hmmm, However, this is my own opinion, sorry for my poor english. Thank you for your suggestion & great work : )
