### ISSUE TITLE
Please, delete the repo

### ISSUE THREAD

**Issue by piecioshka** [sindresorhus/pokemon#3]
Hi @sindresorhus 

I have problem with this project. 

I was created 2 year ago repo https://github.com/piecioshka/pokemon.js which include first 151 Pokémons and returns randomize single name with type of creature.

Today (7 hours ago) created issue https://github.com/piecioshka/pokemon.js/issues/2 which reminds me to create package in `npm`, but you overtake my decision 🤖

My proposals:

* Delete repo,
* Transfer `npm` "pokemon" package name to me

Regards!

**Comment by chrisinajar** [comment]
It's also the same as this: https://www.npmjs.com/package/pokemon-data

**Comment by sindresorhus** [comment]
Please, stop trolling. The name `pokemon` was already taken. I asked npm support to have it since it was name squatted.
