### ISSUE TITLE
Cannot find module "./data/en"

### ISSUE THREAD

**Issue by krypsin** [sindresorhus/pokemon#31]
Just installed this via yarn/npm in my Vue JS project, but it couldn't compile due to the pokemon package not being able to import /data/en.json.

I fixed it by just changing index.js line 3:
`const pokemon = require('./data/en.json');`

**Comment by sindresorhus** [comment]
I assume you're using Webpack. You'll need the JSON loader. You should go complain at the Webpack issue tracker as they're not following the Node.js require resolution logic by default, which wastes the time of both you and me.

https://github.com/webpack/webpack/issues

**Comment by vunb** [comment]
I still got the same issue! This issue should be fixed.

**Comment by drumline18** [comment]
Thank you for fixing this issue at once. I can now delete my own.
