### ISSUE TITLE
French Name could be wrong

### ISSUE THREAD

**Issue by pix674** [sindresorhus/pokemon#38]
Hello,

I do not really know what is the reference for french name.
Mr. Mime (122) in "french pokemon go" is : M. Mime and not Mime.
for pokemon "Type: Null" (772) will it be Type: 0 or Type: Zero ?

**Comment by sindresorhus** [comment]
I don't have time to check this. Link to some sources for your arguments.

**Comment by LuhComZ** [comment]
idk if got fixed but anyways
https://pokemondb.net/pokedex/type-null#dex-lang
https://pokemondb.net/pokedex/mr-mime#dex-lang

**Comment by pix674** [comment]
As you can see this is a screen from the game
[https://i0.wp.com/www.pokemon-france.com/wp-content/uploads/2016/07/M.-Mime-GO.jpg?ssl=1](url)
