### ISSUE TITLE
Add name to error if pokemon does not exist

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/pokemon#5]
I created a list of ids of  rare pokemon based on their names. I had some typos and the package only throws an error indicating that a pokemon with that name does not exist. It would be nice if it showed `Pokemom with name ${name} does not exist` instead.

**Comment by sindresorhus** [comment]
Agreed. I still often slip up when it comes to good error messages.

**Comment by SamVerschueren** [comment]
Same here. Thanks for the improvement :) :beers:
