### ISSUE TITLE
Is there a way to also get IDs using names in lowercase

### ISSUE THREAD

**Issue by PuneetGopinath** [sindresorhus/pokemon#54]
When passing name in getId function, if I pass `pikachu` it doesn't work but if I pass `Pikachu` I get it
So, is there a way to make both the name to lowercase or bring the first letter to UPPERCASE and check with `index` function?
I found this stackoverflow answer useful: https://stackoverflow.com/a/4878800

**Comment by sindresorhus** [comment]
That wouldn't work well for `Type: Null`. I don't think I want to add this here. I'll have to document how the transformation work in all cases and it's just easier for people to do it themselves if you need to be able to use lowercase IDs.
