### ISSUE TITLE
Support for Pokemon with multiple forms

### ISSUE THREAD

**Issue by crownedfoxes** [sindresorhus/pokemon#59]
Would it be possible to add support for Pokemon with multiple forms?

For example, have something like Vulpix-alola or Ponyta-galar? And maybe even support for Pokemon that can change their types with held items, i.e. Arceus and Silvally?

I'd be happy to make the additions if this is approved.

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but I would prefer to keep this package simple. Someone could build using the data provided by this package.

**Comment by crownedfoxes** [comment]
That's fair enough, I did think that myself.
