### ISSUE TITLE
Issue with Indeedee's Simplified Chinese name

### ISSUE THREAD

**Issue by Nate2169** [sindresorhus/pokemon#67]
https://github.com/sindresorhus/pokemon/blob/25b691c31b21c4ec0d14932084209054ab9a8277/data/zh-hans.json#L877

Line 877 contains "À", which is not part of Indeedee's Simplified Chinese name.

**Comment by sindresorhus** [comment]
// @larryyangsen

**Comment by Richienb** [comment]
@sindresorhus Given that the PR linked above was merged, this issue can be closed at your convenience
