### ISSUE TITLE
[Suggestion]  change function getName

### ISSUE THREAD

**Issue by omateusamaral** [sindresorhus/pokemon#69]
why we have a function called getName but we need to pass the id?

![Screenshot from 2022-08-06 20-03-50](https://user-images.githubusercontent.com/37390930/183268551-20a4c2d5-28a0-47ed-87cc-3d06afb38869.png)

For me getName we need to pass the name of pokemon we want.

Example of the function finding by name 

```
exports.getName = (pokemonName, language = 'en') => {
	 const list = getLocalizedList(language);
	const name = list.find(pokemon => pokemon === pokemonName);

	if (!name) {
		throw new Error(`Pokémon with name '${pokemonName}' does not exist. ${reportText}`);
	}

	return name;
};
```

**Comment by sindresorhus** [comment]
The method name describes the return value. There's nothing uncommon about that.
